dist: trusty
language: node_js
node_js:
  - "12"

script:
    - echo "qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,qwertyuiopasdfghjklxcvbnm,"
